os:
  - linux
  - osx

script: 
  - echo $TRAVIS_OS_NAME

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir actions-runner && cd actions-runner; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -O -L https://github.com/actions/runner/releases/download/v2.169.1/actions-runner-osx-x64-2.169.1.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then tar xzf ./actions-runner-osx-x64-2.169.1.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo -e "${token}\n" |  echo -e "\n" |  echo -e "\n" | ./config.sh --url https://github.com/Draco-china/OpenWrt-Actions-R7800 --token ${token}; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./run.sh &; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir actions-runner && cd actions-runner; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -O -L https://github.com/actions/runner/releases/download/v2.169.1/actions-runner-linux-x64-2.169.1.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tar xzf ./actions-runner-linux-x64-2.169.1.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo -e "${token}\n" |  echo -e "\n" |  echo -e "\n" | ./config.sh --url https://github.com/Draco-china/OpenWrt-Actions-R7800 --token ${token}; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./run.sh &; fi

  - while true; do echo -n "This is a test of while loop";date ; sleep 5; done
